name: BedrockCombatCompat
version: 1.0.3
main: io.github.chiefboyardee.bedrockcombat.BedrockCombatPlugin
api-version: 1.21
description: "Cross-platform combat optimization for Geyser/Floodgate servers - controller-friendly combat for Bedrock players, traditional combat for Java players"
author: ChiefBoyardee
website: https://github.com/ChiefBoyardee/BedrockCombatCompat
softdepend: [floodgate, Geyser-Spigot]

commands:
  bedrockcombat:
    description: "Cross-platform combat optimization with PvP/PvE detection"
    usage: "/<command> [player|status|reload]"
    aliases: [bc, bedrockpvp, fastcombat]

permissions:
  bedrockcombat.use:
    description: "Allows using the bedrockcombat toggle command"
    default: op
  bedrockcombat.admin:
    description: "Allows using admin commands (status, reload)"
    default: op
  bedrockcombat.*:
     description: "Grants all BedrockCombat permissions"
     default: op
     children:
       bedrockcombat.use: true
       bedrockcombat.admin: true